export const MAIN_URL = 'http://192.168.10.227:4501/bannayuu/admin/api/v1'
export const LOGIN_API = '/authen/login'
export const CREATE_COMPANY_API = '/company/add'
export const GET_COMPANY_ALL_API = '/company/get-all'
export const GET_COMPANY_BYID_API = '/company/get-by-id'
export const EDIT_COMPANY_INFO_API = '/company/edit-info'
