export const SUCCESS_MESSAGE = 'เรียบร้อย'
export const FAILED_MESSAGE = 'ล้มเหลว'

export const HTTP_FETCHING = 'HTTP_FETCHING'
export const HTTP_SUCCESS = 'HTTP_SUCCESS'
export const HTTP_FAILED = 'HTTP_FAILED'

export const LOGIN_FAILED_MESSAGE = 'Username หรือ Password ไม่ถูกต้อง !'
export const HTTP_LOGIN_CLEARVALUES = 'HTTP_LOGIN_CLEARVALUES'
export const HTTP_LOGIN_FETCHING = 'HTTP_LOGIN_FETCHING'
export const HTTP_LOGIN_SUCCESS = 'HTTP_LOGIN_SUCCESS'
export const HTTP_LOGIN_FAILED = 'HTTP_LOGIN_FAILED'

export const HTTP_LOGOUT_FETCHING = 'HTTP_LOGOUT_FETCHING'
export const HTTP_LOGOUT_SUCCESS = 'HTTP_LOGOUT_SUCCESS'


export const HTTP_GET_COMPANY_ALL_FETCHING = 'HTTP_GET_COMPANY_ALL_FETCHING'
export const HTTP_GET_COMPANY_ALL_SUCCESS = 'HTTP_GET_COMPANY_ALL_SUCCESS'
export const HTTP_GET_COMPANY_ALL_FAILED = 'HTTP_GET_COMPANY_ALL_FAILED'



